[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Methods = "GET", Access-Control-Allow-Headers = "Origin, Host, Content-Type, x-api-key"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/forgot-password/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/verify-email/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/action-center/*"
  to = "/index.html"
  status = 200