[[redirects]]
  force = true
  from = "/sneakers/*"
  to = "/.netlify/functions/sneakers/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/forgot-password/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/verify-email/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/action-center/*"
  to = "/index.html"
  status = 200